Nmcli add options
ansible-collections/community.general pull request #2732
Opened 2021-06-06 18:16 UTC by omula

##### SUMMARY

Add option `routing_rules4` and `may_fail4` which translates to `ipv4.routing-rules` and `ipv4.may-fail` respctively.
Add `disabled` option to method6 to be able to completely disabled IPv6.

Fixes #2730 
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/modules/net_tools/nmcli.py

2021-06-06 18:42 UTC, aminvakil reviewed
Thanks for adding this!
Also add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

2021-06-06 18:42 UTC, aminvakil commented on plugins/modules/net_tools/nmcli.py
> +        type: str
Also for other options.
```suggestion
        type: str
        version_added: 3.2.0
```

2021-06-06 18:42 UTC, aminvakil commented on plugins/modules/net_tools/nmcli.py
> +        default: yes
```suggestion
        default: true
```

2021-06-08 10:42 UTC, felixfontein commented on changelogs/fragments/2732-nmcli_add_options.yml
> +  - nmcli - Add option routing_rules4 and may_fail4 (https://github.com/ansible-collections/community.general/issues/2730).
```suggestion
  - nmcli - add options ``routing_rules4`` and ``may_fail4`` (https://github.com/ansible-collections/community.general/issues/2730).
```

2021-06-08 10:42 UTC, felixfontein commented on changelogs/fragments/2732-nmcli_add_options.yml
> +  - nmcli - Add disabled option to method6 (https://github.com/ansible-collections/community.general/issues/2730).
```suggestion
  - nmcli - add ``disabled`` value to ``method6`` option (https://github.com/ansible-collections/community.general/issues/2730).
```

2021-06-08 10:42 UTC, felixfontein commented on plugins/modules/net_tools/nmcli.py
>              - If I(ip6) is set, C(ipv6.method) is automatically set to C(manual) and this parameter is not needed.
```suggestion
            - If I(ip6) is set, C(ipv6.method) is automatically set to C(manual) and this parameter is not needed.
            - C(disabled) was added in community.general 3.2.0.
```

2021-06-08 10:43 UTC, felixfontein commented
(There are currently CI problems, probably caused by the fastly.com outage.)

2021-06-10 07:33 UTC, omula commented
Thanks for all your suggestions. Is there anything pending to fix that I might have missed?

2021-06-10 10:55 UTC, felixfontein commented
@omula the unit tests are failing, these have to be fixed.

2021-06-16 19:26 UTC, felixfontein commented on plugins/modules/net_tools/nmcli.py
> +            - If you need I(ip4) configured before network-online.target is reached, set the the property to no.
```suggestion
            - If you need I(ip4) configured before C(network-online.target) is reached, set this option to C(false).
```

2021-06-16 19:26 UTC, felixfontein commented on plugins/modules/net_tools/nmcli.py
> +            - Is the same as in an 'ip route add' command, except always requires specifying a priority.
```suggestion
            - Is the same as in an C(ip route add) command, except always requires specifying a priority.
```
Can you add an example using this option (and potentially also the others)? I think that would help understanding what this does.

2021-06-17 09:15 UTC, aminvakil requested changes

2021-06-17 09:15 UTC, aminvakil commented on changelogs/fragments/2732-nmcli_add_options.yml
> +  - nmcli - add options ``routing_rules4`` and ``may_fail4`` (https://github.com/ansible-collections/community.general/issues/2730).
```suggestion
  - nmcli - add ``routing_rules4`` and ``may_fail4`` options (https://github.com/ansible-collections/community.general/issues/2730).
```

2021-06-17 09:15 UTC, aminvakil commented on plugins/modules/net_tools/nmcli.py
> +        version_added: 3.2.0
Unfortunately 3.2.0 has been released and this PR didn't make it for that.
```suggestion
        version_added: 3.3.0
```

2021-06-17 09:15 UTC, aminvakil commented on plugins/modules/net_tools/nmcli.py
> +        version_added: 3.2.0
Here too.
```suggestion
        version_added: 3.3.0
```

2021-06-17 09:15 UTC, aminvakil commented on plugins/modules/net_tools/nmcli.py
> +            - C(disabled) was added in community.general 3.2.0.
Also here.
```suggestion
            - C(disabled) was added in community.general 3.3.0.
```

2021-06-18 08:36 UTC, aminvakil approved these changes
Thanks for adding these options!

2021-06-18 20:01 UTC, felixfontein approved these changes

2021-06-19 12:42 UTC, merged

2021-06-19 12:42 UTC, felixfontein commented
@omula thanks for adding this!
@aminvakil thanks for reviewing!