Add option to the keycloak_client module
ansible-collections/community.general pull request #2949
Opened 2021-07-07 07:45 UTC by Gaetan2907

##### SUMMARY
Add `authentication_flow_binding_overrides` option to the keycloak_client module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`keycloak_client.py`

##### ADDITIONAL INFORMATION
It is now possible to use the `authentication_flow_binding_overrides` option, like on the following example: 

```
- name: Create or update a Keycloak client (with authentication_flow_binding_override)
  community.general.keycloak_client:
    auth_keycloak_url: https://auth.example.com/auth
    token: "{{ access_token }}"
    state: present
    realm: master
    client_id: test
    authentication_flow_binding_override:
        browser: 4c90336b-bf1d-4b87-916d-3677ba4e5fbb
```
New feature tested on Keycloak 8.0.1.

2021-07-07 09:47 UTC, aminvakil requested changes
Thanks for adding this!
Maybe you forgot to push the actual code that does this change? :)

2021-07-07 09:47 UTC, aminvakil commented on changelogs/fragments/2949-add_authentication-flow-binding_keycloak-client.yml
> +  - keycloak_client - add authentication_flow_binding_overrides option to the keycloak_client module (https://github.com/ansible-collections/community.general/pull/2949).
```suggestion
  - keycloak_client - add ``authentication_flow_binding_overrides`` option (https://github.com/ansible-collections/community.general/pull/2949).
```

2021-07-07 09:47 UTC, aminvakil commented on plugins/modules/identity/keycloak/keycloak_client.py
> +            - authenticationFlowBindingOverrides
```suggestion
            - authenticationFlowBindingOverrides
        version_added: 3.4.0
```

2021-07-07 09:52 UTC, Gaetan2907 commented
> Maybe you forgot to push the actual code that does this change? :)

No more code need to be added, the parameter is automatically included in the API call

2021-07-07 09:55 UTC, aminvakil commented
> > Maybe you forgot to push the actual code that does this change? :)
> 
> No more code need to be added, the parameter is automatically included in the API call

Right, I didn't know about the magic this module does! ;)

2021-07-07 09:56 UTC, aminvakil commented on plugins/modules/identity/keycloak/keycloak_client.py
> +    authentication_flow_binding_override:
```suggestion
    authentication_flow_binding_overrides:
```

2021-07-07 10:13 UTC, Gaetan2907 commented on plugins/modules/identity/keycloak/keycloak_client.py
> +    authentication_flow_binding_override:
Nice catch ! :)

2021-07-07 10:25 UTC, aminvakil requested changes
LGTM
I'm just blocking this from getting merged until we decide whether we want to release 3.3.2 or not.

2021-07-07 11:41 UTC, felixfontein reviewed
It would be nice to have a test for this new parameter.

2021-07-07 19:14 UTC, felixfontein approved these changes

2021-07-08 10:05 UTC, aminvakil approved these changes
LGTM

2021-07-09 06:33 UTC, merged

2021-07-09 06:33 UTC, felixfontein commented
@Gaetan2907 thanks for implementing this!
@aminvakil thanks for reviewing!