Keycloak: Improve diff mode on keycloak_authentication module
ansible-collections/community.general pull request #2963
Opened 2021-07-09 09:55 UTC by Gaetan2907

##### SUMMARY
The diff mode is now showing `before` and `after` state also when updating the authentication flow. Before the diff state was only displayed on the creation of a new authentication flow.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
`keycloak_authentication.py`

##### ADDITIONAL INFORMATION
The function `create_or_update_executions(kc, config, realm='master')` is now returning `dict(before='', after'')` if modifications have been done or `None` if no changes.

2021-07-09 14:43 UTC, Ajpantuso requested changes
The primary request is to only return `diff` in the `result` dict when `diff` mode is enabled and when `diff` mode is enabled `before` and `after` should always be returned even if there are no changes. Other comments are just for clarity in documentation.

2021-07-09 14:43 UTC, Ajpantuso commented on plugins/modules/identity/keycloak/keycloak_authentication.py
> +                result['diff'] = diff
```suggestion
            changed, diff = create_or_update_executions(kc=kc, config=new_auth_repr, realm=realm)
            result['changed'] = changed
            if module._diff:
                result['diff'] = diff
```

2021-07-09 14:43 UTC, Ajpantuso commented on plugins/modules/identity/keycloak/keycloak_authentication.py
> +        return dict(before=before, after=after) if changed else None
```suggestion
        return changed, dict(before=before, after=after)
```

2021-07-09 14:43 UTC, Ajpantuso commented on plugins/modules/identity/keycloak/keycloak_authentication.py
> +    :return: Dict with key "before" and "after" to describe the changes, None if no modification
This should return a tuple.

2021-07-09 14:43 UTC, Ajpantuso commented on changelogs/fragments/2963-improve-diff-mode-on-keycloak_authentication.yml
> +- keycloak_authentication - diff mode is now displaying before and after state also when the authentication flow is updated (https://github.com/ansible-collections/community.general/pull/2963).
```suggestion
- keycloak_authentication - enhanced diff mode to also return before and after state when the authentication flow is updated (https://github.com/ansible-collections/community.general/pull/2963).
```

2021-07-10 12:52 UTC, Gaetan2907 commented on plugins/modules/identity/keycloak/keycloak_authentication.py
> +    :return: Dict with key "before" and "after" to describe the changes, None if no modification
Resolved with commit 350e782

2021-07-10 12:53 UTC, Gaetan2907 commented
@Ajpantuso thanks a lot for the review !

2021-07-10 16:39 UTC, Ajpantuso requested changes
One thing a missed the first time, but otherwise this looks good.

2021-07-10 16:39 UTC, Ajpantuso commented on plugins/modules/identity/keycloak/keycloak_authentication.py
> +            result['changed'] = changed
```suggestion
            result['changed'] |= changed
```
Sorry missed this the first time. If `force=True` I think `create_or_update_executions` will always return `changed=True`, but this should help prevent regressions.

2021-07-12 12:22 UTC, Ajpantuso approved these changes
LGTM, thanks.

2021-07-13 04:57 UTC, felixfontein approved these changes

2021-07-13 04:57 UTC, merged

2021-07-13 04:57 UTC, felixfontein commented
@Gaetan2907 thanks for improving this!
@Ajpantuso thanks for reviewing!