Easy fix
ansible-collections/community.general pull request #3052
Opened 2021-07-23 05:19 UTC by trhr

##### SUMMARY
Plugin was crashing on this line on Python 3.9.2 deployed on qemu image with debian bullseye. It doesn't crash anymore.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.general.proxmox

##### ADDITIONAL INFORMATION
I suspect you'll grasp it.

2021-07-23 06:15 UTC, felixfontein commented
Thanks for your contribution! Can you please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)?

2021-07-23 11:06 UTC, russoz approved these changes
Looking good to me

2021-07-23 11:52 UTC, Ajpantuso commented
This fixes #2957 for which the same solution was proposed.
It would be nice to understand why template is not a required field in the `qemu.conf` causing the failure, but it can remain a mystery for now. Will approve when changelog fragment is added.

2021-07-24 01:16 UTC, Ajpantuso requested changes
Improved change description for anyone looking for this fix in the changelog.

2021-07-24 01:16 UTC, Ajpantuso commented on changelogs/fragments/3052_proxmox_inventory_plugin.yml
> +  - proxmox_inventory_plugin - It would be nice to understand why template is not a required field in the qemu.conf causing the failure, but it can remain a mystery for now (https://github.com/ansibl
```suggestion
  - proxmox inventory plugin - fixed plugin failure when a ``qemu`` guest has no ``template`` key (https://github.com/ansible-collections/community.general/pull/3052).
```

2021-07-24 01:38 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-07-24 18:40 UTC, merged

2021-07-24 18:40 UTC, felixfontein commented
@trhr thanks for fixing this!
@russoz @Ajpantuso thanks for reviewing!