manage dummy connections
ansible-collections/community.general pull request #3132
Opened 2021-08-01 13:47 UTC by rekup

##### SUMMARY
Add ability to manage dummy interfaces using the `nmcli` module

Fixes https://github.com/ansible-collections/community.general/issues/724

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
nmcli

##### ADDITIONAL INFORMATION
- add ability to manage dummy interfaces

2021-08-04 06:36 UTC, felixfontein commented
Please note that the tests currently have a conflict due to #3081 being merged.

CC @Ajpantuso @hummeltech maybe this PR is of interest to you as well.

2021-08-04 12:48 UTC, Ajpantuso requested changes
The test conflicts are just because the additions occupy the same space. I would pull out the tests for this PR to a scratch file, rebase, and then add the tests back. Otherwise looks okay to me.

2021-08-04 12:48 UTC, Ajpantuso commented on changelogs/fragments/3132-nmcli-dummy.yaml
> +  - nmcli - add dummy interface support (https://github.com/ansible-collections/community.general/issues/724).
```suggestion
  - nmcli - add ``dummy`` interface support (https://github.com/ansible-collections/community.general/issues/724).
```

2021-08-04 23:51 UTC, hummeltech approved these changes
Looks good!

2021-08-05 12:08 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-08-05 12:25 UTC, felixfontein approved these changes

2021-08-05 12:25 UTC, merged

2021-08-05 12:26 UTC, felixfontein commented
@rekup thanks for contributing this!
@Ajpantuso @hummeltech thanks for reviewing!