nmcli: Fix change detection for Wi-Fi security options
ansible-collections/community.general pull request #3136
Opened 2021-08-03 01:02 UTC by hummeltech

##### SUMMARY

Fixed issue in which modifying the value of `wifi_sec` would not produce any change.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`net_tools/nmcli.py`

##### ADDITIONAL INFORMATION

I.E. Changing from this:
  ```YAML
    community.general.nmcli:
      type: wifi
      ifname: wlp4s0
      ssid: Brittany
      wifi_sec:
        key-mgmt: wpa-psk
        psk: crash-landing
  ```
To this:
  ```YAML
    community.general.nmcli:
      type: wifi
      ifname: wlp4s0
      ssid: Brittany
      wifi_sec:
        key-mgmt: sae
        psk: pefect-landing
  ```
You would expect something like this, but instead get nothing.
  ```diff
  --- before
  +++ after
   {
  ...
  -    "802-11-wireless-security.key-mgmt": "wpa-psk",
  -    "802-11-wireless-security.psk": "crash-landing",
  +    "802-11-wireless-security.key-mgmt": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
  +    "802-11-wireless-security.psk": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
  ...
   }
  ```

2021-08-03 16:51 UTC, hummeltech commented
I'll rebase on `main` once #3081 is merged in.

2021-08-05 16:55 UTC, Ajpantuso requested changes
Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) as well.

2021-08-05 16:55 UTC, Ajpantuso commented on plugins/modules/net_tools/nmcli.py
> +              C({key-mgmt: wpa-psk, psk: my_password})'
```suggestion
            - 'The security configuration of the WiFi connection. The valid attributes are listed on:
              U(https://networkmanager.dev/docs/api/latest/settings-802-11-wireless-security.html).'
            - 'For instance to use common WPA-PSK auth with a password:
              C({key-mgmt: wpa-psk, psk: my_password}).'
```

2021-08-06 12:23 UTC, Ajpantuso requested changes
Outside of addressing the command argument duplication this looks good.

2021-08-06 12:23 UTC, Ajpantuso commented on plugins/modules/net_tools/nmcli.py
> +                    cmd += ['802-11-wireless-security.%s' % name, value]
As per your [suggestion](https://github.com/ansible-collections/community.general/issues/3145#issuecomment-894003609) it probably makes sense to remove the argument duplication in this PR. Better to restrict the bugfix to just passing the password via `stdin`

2021-08-06 19:10 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-08-07 13:20 UTC, merged

2021-08-07 13:21 UTC, felixfontein commented
@hummeltech thanks for implementing this!
@Ajpantuso thanks for reviewing!