Updated the plugin to reflect breaking changes introduced in the underpinning SDK
ansible-collections/community.general pull request #3139
Opened 2021-08-03 13:40 UTC by EndlessTrax

##### SUMMARY
This PR updates the plugin to bring it in line with the current `python-tss-sdk` version, which added breaking changes in v1.0.0. The plugin is now compatible with the latest SDK version.  

This also fixes #3057. 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`tss` lookup plugin

##### ADDITIONAL INFORMATION
No changes are needed to current playbooks, as inputs have stayed the same. Users will be encouraged to update their `python-tss-sdk` version to >1.0.0.

2021-08-03 15:08 UTC, amigus commented
Ricky's changes should fix the problem so this PR is GTG from our perspective. Please merge if you are good with it.

2021-08-03 21:09 UTC, Ajpantuso requested changes
Besides the comment on compatibility where will users be encouraged to upgrade to version `1.0.0`?

2021-08-03 21:09 UTC, Ajpantuso commented on plugins/lookup/tss.py
> +        )
```suggestion
        if LooseVersion(thycotic_version) < LooseVersion('1.0.0'):
            return SecretServer(**server_parameters)
            
        authorizer = PasswordGrantAuthorizer(
            server_parameters["base_url"],
            server_parameters["username"],
            server_parameters["password"],
            server_parameters["token_path_uri"],
        )
```

`token_path_uri` is not a valid argument in `0.0.6` so preserving the existing behavior for versions < `1.0.0` should give appropriate time for deprecation (thycotic_version = `thycotic.__version__`). See [here](https://github.com/thycotic/python-tss-sdk/blob/9727ffea263fd29ed7cb0a64325a95a735162365/thycotic/secrets/server.py#L187-L193)

2021-08-04 06:30 UTC, felixfontein commented
You also need a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

2021-08-05 14:55 UTC, EndlessTrax commented
Thanks for the feedback @felixfontein. I've made updates as suggested. Let me know if there is anything else needed before merging. Cheers. 

cc: @amigus

2021-08-05 16:11 UTC, Ajpantuso requested changes
Other than the changelog fragment this looks good.

2021-08-05 16:11 UTC, Ajpantuso commented on changelogs/fragments/3139-tss-lookup-plugin-update-to-make-compatible-with-sdk-v1.yml
> +    (https://github.com/ansible-collections/community.general/pull/3139)
```suggestion
  - tss lookup plugin - fixed incompatibility with ``python-tss-sdk`` version 1.0.0
    (https://github.com/ansible-collections/community.general/issues/3057, https://github.com/ansible-collections/community.general/pull/3139).
```

2021-08-05 17:28 UTC, merged

2021-08-05 17:29 UTC, felixfontein commented
@EndlessTrax thanks for fixing this!
@amigus @Ajpantuso thanks for reviewing!

2021-08-05 17:29 UTC, Ajpantuso approved these changes
LGTM, thanks!