openbsd_pkg: Fix regexp matching crash
ansible-collections/community.general pull request #3161
Opened 2021-08-06 18:48 UTC by zorun

Fix regexp crash caused by missing escaping of package name.

##### SUMMARY

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
openbsd_pkg

##### ADDITIONAL INFORMATION
When a package name contains special characters (e.g. "g++"), they are
interpreted as part of the regexp.

This can lead to a crash with an error in the python re module, for
instance with "g++":

    sre_constants.error: multiple repeat

Fix this by escaping the package name.

2021-08-06 18:50 UTC, zorun commented
This bug is present since the beginning of this repo (I haven't checked in the previous ansible repo), so it would be nice to backport the fix to stable releases if it makes sense.

2021-08-06 19:45 UTC, eest commented
Hello @zorun, thanks for reporting this issue! It indeed looks like a bug and your fix looks good from a cursory review. I’ll get back to you when I have been able to properly review and test this locally 🙂.

2021-08-07 00:29 UTC, Ajpantuso requested changes
Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). Unit tests for this fix would be nice as well to demonstrate it's effectiveness and avoid future regressions. If you don't want to write tests for the full `package_present` and `package_latest` functions I would wrap these regex tests into functions which just return a `bool` based on the search result. And since the last feature was added in community,general 1.3.0 I don't think backporting will be an issue. Thanks!

2021-08-08 16:37 UTC, zorun commented
> Hello @zorun, thanks for reporting this issue! It indeed looks like a bug and your fix looks good from a cursory review. I’ll get back to you when I have been able to properly review and test this locally slightly_smiling_face.

Thanks!

If you want to reproduce, I should mention that I triggered this bug when the package is **not** found. It triggered while trying to install `g++` on OpenBSD/mips, where it does not exist. This was on gcc231 here: https://cfarm.tetaneutral.net/machines/list/

2021-08-08 16:39 UTC, zorun commented
> Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). Unit tests for this fix would be nice as well to demonstrate it's effectiveness and avoid future regressions. If you don't want to write tests for the full `package_present` and `package_latest` functions I would wrap these regex tests into functions which just return a `bool` based on the search result. And since the last feature was added in community,general 1.3.0 I don't think backporting will be an issue. Thanks!

I added a changelog entry, thanks for the pointer.

About tests, I didn't find any existing unit test for openbsd_pkg. Do you have pointers to documentation or a simple test I could use as a template?

2021-08-08 16:40 UTC, felixfontein commented on changelogs/fragments/3161-openbsd-pkg-fix-regexp-matching-crash.yml
> +  - openbsd_pkg - Fix regexp matching crash. This bug could trigger on package names with special characters, for example ``g++`` (https://github.com/ansible-collections/community.general/pull/3161).
```suggestion
  - openbsd_pkg - fix regexp matching crash. This bug could trigger on package names with special characters, for example ``g++`` (https://github.com/ansible-collections/community.general/pull/3161).
```

2021-08-08 16:41 UTC, zorun commented on changelogs/fragments/3161-openbsd-pkg-fix-regexp-matching-crash.yml
> +  - openbsd_pkg - Fix regexp matching crash. This bug could trigger on package names with special characters, for example ``g++`` (https://github.com/ansible-collections/community.general/pull/3161).
fixed

2021-08-08 17:39 UTC, Ajpantuso commented
> About tests, I didn't find any existing unit test for openbsd_pkg. Do you have pointers to documentation or a simple test I could use as a template?

The `Homebrew` module has a simple [unit test](https://github.com/ansible-collections/community.general/blob/main/tests/unit/plugins/modules/packaging/os/test_homebrew.py) for one of it's functions that might help you get started.

2021-08-09 14:51 UTC, felixfontein commented
FYI: 3.5.0 and 2.5.5 will be released tomorrow. @eest if you can confirm that this fix works by then, I'll gladly include it even if there are no tests yet. (The change looks safe enough to me that it's ok to add the tests later.)

2021-08-09 18:17 UTC, eest commented
> If you want to reproduce, I should mention that I triggered this bug when the package is **not** found. It triggered while trying to install `g++` on OpenBSD/mips, where it does not exist. This was on gcc231 here: https://cfarm.tetaneutral.net/machines/list/

Thanks for the pointer, I don't have access to a `mips` machine but I could instead reproduce it on `amd64` by adding a third plus sign. The result before your fix:
```
$ ansible testservers -u root -m openbsd_pkg -a "name=g+++ state=present"
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of
code and can become unstable at any point.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: re.error: multiple repeat at position 4
192.168.1.60 | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.1.60 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628524855.9675233-81581-139529110244626/AnsiballZ_openbsd_pkg.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628524855.9675233-81581-139529110244626/AnsiballZ_openbsd_pkg.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628524855.9675233-81581-139529110244626/AnsiballZ_openbsd_pkg.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.openbsd_pkg', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.openbsd_pkg', _modlib_path=modlib_path),\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_openbsd_pkg_payload_x95_4gkl/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 653, in <module>\r\n  File \"/tmp/ansible_openbsd_pkg_payload_x95_4gkl/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 605, in main\r\n  File \"/tmp/ansible_openbsd_pkg_payload_x95_4gkl/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 244, in package_present\r\n  File \"/usr/local/lib/python3.9/re.py\", line 201, in search\r\n    return _compile(pattern, flags).search(string)\r\n  File \"/usr/local/lib/python3.9/re.py\", line 304, in _compile\r\n    p = sre_compile.compile(pattern, flags)\r\n  File \"/usr/local/lib/python3.9/sre_compile.py\", line 764, in compile\r\n    p = sre_parse.parse(p, flags)\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 948, in parse\r\n    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 443, in _parse_sub\r\n    itemsappend(_parse(source, state, verbose, nested + 1,\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 671, in _parse\r\n    raise source.error(\"multiple repeat\",\r\nre.error: multiple repeat at position 4\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
... and after your fix:
```
$ ansible testservers -u root -m openbsd_pkg -a "name=g+++ state=present"
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of
code and can become unstable at any point.
192.168.1.60 | FAILED! => {
    "build": false,
    "changed": false,
    "msg": "Can't find g+++\n",
    "name": [
        "g+++"
    ],
    "state": "present"
}
```
A clear improvement :slightly_smiling_face: .

As for the other instance you fixed, given that `g++` was already installed it could be verified by trying to run `state=latest`:
```
$ ansible testservers -u root -m openbsd_pkg -a "name=g++ state=latest"
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of
code and can become unstable at any point.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: re.error: multiple repeat at position 4
192.168.1.60 | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.1.60 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628528067.6084132-82123-205939577525348/AnsiballZ_openbsd_pkg.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628528067.6084132-82123-205939577525348/AnsiballZ_openbsd_pkg.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1628528067.6084132-82123-205939577525348/AnsiballZ_openbsd_pkg.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.openbsd_pkg', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.openbsd_pkg', _modlib_path=modlib_path),\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_openbsd_pkg_payload_twyguv_g/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 653, in <module>\r\n  File \"/tmp/ansible_openbsd_pkg_payload_twyguv_g/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 609, in main\r\n  File \"/tmp/ansible_openbsd_pkg_payload_twyguv_g/ansible_openbsd_pkg_payload.zip/ansible_collections/community/general/plugins/modules/openbsd_pkg.py\", line 298, in package_latest\r\n  File \"/usr/local/lib/python3.9/re.py\", line 201, in search\r\n    return _compile(pattern, flags).search(string)\r\n  File \"/usr/local/lib/python3.9/re.py\", line 304, in _compile\r\n    p = sre_compile.compile(pattern, flags)\r\n  File \"/usr/local/lib/python3.9/sre_compile.py\", line 764, in compile\r\n    p = sre_parse.parse(p, flags)\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 948, in parse\r\n    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 443, in _parse_sub\r\n    itemsappend(_parse(source, state, verbose, nested + 1,\r\n  File \"/usr/local/lib/python3.9/sre_parse.py\", line 671, in _parse\r\n    raise source.error(\"multiple repeat\",\r\nre.error: multiple repeat at position 4\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
... and again with the fix:
```
$ ansible testservers -u root -m openbsd_pkg -a "name=g++ state=latest"
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of
code and can become unstable at any point.
192.168.1.60 | SUCCESS => {
    "build": false,
    "changed": false,
    "name": [
        "g++"
    ],
    "state": "latest" [...]

2021-08-09 20:44 UTC, merged

2021-08-09 20:45 UTC, felixfontein commented
@zorun thanks a lot for fixing this!
@Ajpantuso @eest thanks a lot for reviewing and testing this!

2021-08-12 11:45 UTC, zorun commented
Excellent, thanks for the in-depth review @eest !