redfish_info: Include Status property for GetChassisThermals
ansible-collections/community.general pull request #3233
Opened 2021-08-17 16:35 UTC by jyundt

Include Status property for Thermal objects when querying Thermal properties
via GetChassisThermals command.

FIXES #3232

##### SUMMARY
Previously the Status property was not included in the list of valid properties. Adding this property will allow users to determine the state/status/health/presence of thermal sensors.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
redfish_utils.py

##### ADDITIONAL INFORMATION

### Sample below of a chassis reporting thermal sensor info using collections `3.5.0`:

```
(ansible_collections) [jyundt@aurora tests]$ cat rf_thermal.yml 
---
- hosts: all
  gather_facts: false
  vars:
    bmc_username: admin
    bmc_password: hunter2
    bmc_address: 1.1.1.1
    default_uri_timeout: 5
    default_uri_retries: 5
  tasks:
  - name: gather stuff
    community.general.redfish_info:
      category: Chassis
      command: GetChassisThermals
      baseuri: "{{ bmc_address }}"
      username: "{{ bmc_username }}"
      password: "{{ bmc_password }}"
      timeout: "{{ default_uri_timeout }}"
    retries: "{{ default_uri_retries }}"
    register: redfish_results
  - debug:
      var: redfish_results
(ansible_collections) [jyundt@aurora tests]$ ansible-galaxy  collection install community.general:3.5.0 --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'community.general:3.5.0' to '/home/jyundt/.ansible/collections/ansible_collections/community/general'
Downloading https://galaxy.ansible.com/download/community-general-3.5.0.tar.gz to /home/jyundt/.ansible/tmp/ansible-local-3689178dboet3s/tmp0xd3ldry
community.general (3.5.0) was installed successfully
(ansible_collections) [jyundt@aurora tests]$ time ansible-playbook -i localhost, rf_thermal.yml 

PLAY [all] *********************************************************************************************************************************

TASK [gather stuff] ************************************************************************************************************************
[DEPRECATION WARNING]: Distribution redhat 8.4 on host localhost should use /usr/libexec/platform-python, but is using /usr/bin/python for 
backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this 
host. See https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information. This feature will be 
removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "redfish_results": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        },
        "changed": false,
        "deprecations": [
            {
                "msg": "Distribution redhat 8.4 on host localhost should use /usr/libexec/platform-python, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information",
                "version": "2.12"
            }
        ],
        "failed": false,
        "redfish_facts": {
            "thermals": {
                "entries": [
                    {
                        "LowerThresholdCritical": 5,
                        "LowerThresholdFatal": 5,
                        "MaxReadingRangeTemp": 98,
                        "MinReadingRangeTemp": 3,
                        "Name": "CPU1 Temp",
                        "PhysicalContext": "CPU",
                        "ReadingCelsius": 51,
                        "RelatedItem": [
                            {
                                "@odata.id": "/redfish/v1/Systems/1/Processors/1"
                            }
                        ],
                        "SensorNumber": 1,
                        "UpperThresholdCritical": 96,
                        "UpperThresholdFatal": 96
                    },
                    {
                        "LowerThresholdCritical": 5,
                        "LowerThresholdFatal": 5,
                        "MaxReadingRangeTemp": 98,
                        "MinReadingRangeTemp": 3,
                        "Name": "CPU2 Temp",
                        "PhysicalContext": "CPU",
                        "ReadingCelsius": 45,
                        "RelatedItem": [
                            {
                                "@odata.id": "/redfish/v1/Systems/1/Processors/2"
                            }
                        ],
                        "SensorNumber": 2,
                        "UpperThresholdCritical": 96,
                        "UpperThresholdFatal": 96
                    },
                    {
                        "LowerThresholdCritical": 0,
                        "LowerThresholdFatal": 0,
                        "MaxReadingRangeTemp": 0,
                        "MinReadingRangeTemp": 0,
                        "Name": "Inlet Temp",
                        "PhysicalContext": "SystemBoard",
                        "ReadingCelsius": 0,
                        "RelatedItem": [
                            {
                                "@odata.id": "/redfish/v1/Chassis/1"
                            },
                            {
                                "@odata.id": "/redfish/v1/Systems/1"
                            }
                        ],
                        "SensorNumber": 9,
                        "UpperThresholdCritical": 0,
                        "UpperThresholdFatal": 0
                    },
                    {
                        "LowerThresholdCritical": 5,
                        "LowerThresholdFatal": 5,
                        "MaxReadingRangeTemp": 107,
                        "MinReadingRangeTemp": 3,
                        "Name": "PCH Temp",
                        "PhysicalContext": "SystemBoard",
                        "ReadingCelsius": 42,
                        "RelatedItem": [
                            {
                                "@odata.id": "/redfish/v1/Chassis/1"
                            },
                            {
                                "@odata.id": "/redfish/v1/Systems/1"
                            }
                        ],
                        "SensorNumber": 10,
                        "UpperThresholdCritical": 90,
                        "UpperThresholdFatal": 105
                    },
                    {
                        "LowerThresholdCritical": 5,
                        "LowerThresholdFatal": 5,
                        "MaxReadingRangeTemp": 92,
                        "MinReadingRangeTemp": 3,
                        "Name": "System Temp",
                        "PhysicalContext": "SystemBoard",
                        "ReadingCelsius": 34,
                        "RelatedItem": [
                            {
                                "@odata.id": "/redfish/v1/Chassis/1"
                            },
                            {
                                "@odata.id": "/redfish/v1/Systems/1"
                            }
                        ],
                        "SensorNumber": 11,
                        "UpperThresholdCritical": 85,
                        "UpperThresholdFatal": 90
                    },
                    {
                        "LowerThresholdCritical": 5,
                        "LowerThresholdFatal": 5,
                        "MaxReadingRangeTemp": 92,
                        "MinReadingRangeTemp": 3,
                        "Name": "Peripheral Temp",
                        "PhysicalContext": "SystemBoard",
           [...]

2021-08-17 16:59 UTC, mraineri commented
Thanks for the contribution. Looks good; will wait to see if the community maintainers have things to note with regards to the changelog or other comments that should be added. Will add ship it tag otherwise.

2021-08-17 17:02 UTC, xmadsen commented
Looks good to me. Thanks for adding this @jyundt ! 👍

2021-08-17 21:55 UTC, Ajpantuso requested changes
Thanks for your contribution. Other than the changelog fragment this looks good.

2021-08-17 21:55 UTC, Ajpantuso commented on changelogs/fragments/3233-include-thermal-sensor-status-via-redfish_info.yaml
> +  - redfish_info - Include Status property for Thermal objects when querying Thermal properties via GetChassisThermals command (https://github.com/ansible-collections/community.general/issues/3232)
```suggestion
  - redfish_info - include ``Status`` property for Thermal objects when querying Thermal properties via ``GetChassisThermals`` command (https://github.com/ansible-collections/community.general/issues/3232).
```

2021-08-19 13:11 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-08-19 13:12 UTC, mraineri commented
shipit

2021-08-19 19:13 UTC, merged

2021-08-19 19:13 UTC, felixfontein commented
@jyundt thanks for your contribution!
@mraineri @Ajpantuso thanks for reviewing!