Adding mutual authentication support and updating authentication parameters description
ansible-collections/community.general pull request #3422
Opened 2021-09-23 08:21 UTC by ricsanfre

##### SUMMARY

Updating confusing description of authentication parameters included in documentation section
and adding the capability to specify mutual authentication between target and initiator

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/modules/system/open_iscsi.py

##### ADDITIONAL INFORMATION

node_auth, node_pass and node_user parameters are used for target login, not for target discovery. Authentication can be set for both procedures (discovery and login) but module current implementation does not support discovery authentication and thus parameters descriptions are confusing.

Adding two new module parameters (node_user_in, node_pass_in) to support mutual authentication.

2021-09-23 18:02 UTC, Ajpantuso requested changes
Thanks for your contribution! Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) as well.

2021-09-23 18:02 UTC, Ajpantuso commented on plugins/modules/system/open_iscsi.py
> +                module.fail_json(cmd=cmd, rc=rc, msg=err)
```suggestion
            module.run_command(cmd, check_rc=True)
```

2021-09-24 08:40 UTC, ricsanfre commented on plugins/modules/system/open_iscsi.py
> +        type: str
Updated

2021-09-24 08:40 UTC, ricsanfre commented on plugins/modules/system/open_iscsi.py
>          type: str
Updated

2021-09-24 08:41 UTC, ricsanfre commented on plugins/modules/system/open_iscsi.py
>          type: str
changelog fragment also created

2021-09-24 13:43 UTC, Ajpantuso requested changes
Other than the superfluous Changelog item this looks good to me.

2021-09-24 13:43 UTC, Ajpantuso commented on changelogs/fragments/3422-open-iscsi-mutual-authentication-support.yaml
> +  - open-iscsi - Updating confusing parameters descriptions node_user and node_pass (https://github.com/ansible-collections/community.general/pull/3422).
```suggestion
```
Changelog items are not required for doc only changes.

2021-09-25 14:02 UTC, Ajpantuso requested changes
One last changelog item.

2021-09-25 14:02 UTC, Ajpantuso commented on changelogs/fragments/3422-open-iscsi-mutual-authentication-support.yaml
> +  - open-iscsi - Adding support for mutual authentication between target and initiator (https://github.com/ansible-collections/community.general/pull/3422).
```suggestion
  - open-iscsi - adding support for mutual authentication between target and initiator (https://github.com/ansible-collections/community.general/pull/3422).
```

2021-09-25 23:39 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-09-26 11:38 UTC, merged

2021-09-26 11:38 UTC, felixfontein commented
@ricsanfre thanks for implementing this!
@Ajpantuso thanks for reviewing!