Adding capability to specify ehlo hostname
ansible-collections/community.general pull request #3425
Opened 2021-09-23 15:35 UTC by j20d

##### SUMMARY
The mail module is missing the capability to configure the hostname used for EHLO.
Being able to configure that allows for greater flexibility

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

mail
##### ADDITIONAL INFORMATION
Currently the hostname used for EHLO is automatically deduced by smtplib.
If you have a restrictive mailsetup the mailserver may try to validate the EHLO.
Adding capability to specify the hostname used for EHLO allows for usage from behind routers/nat-gateways.

2021-09-23 17:35 UTC, Ajpantuso requested changes
Thanks for your contribution! Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) as well.

2021-09-23 17:35 UTC, Ajpantuso commented on plugins/modules/notification/mail.py
> +    type: str
```suggestion
  ehlohost:
    description:
    - Allows for manual specification of host for EHLO.
    type: str
    version_added: 3.8.0
```

2021-09-23 20:35 UTC, Ajpantuso requested changes
Outside of the changelog this looks good. I don't think this is a candidate for [integration tests](https://github.com/ansible-collections/community.general/blob/main/tests/integration/targets/mail/tasks/main.yml) given the nature of the feature, but please take a look and confirm.

2021-09-23 20:35 UTC, Ajpantuso commented on changelogs/fragments/3425-mail_add_configurable_ehlo_hostname.yml
> +  - mail - add new property ``ehlohost``, allowing for manual override of host used in SMTP EHLO (https://github.com/ansible-collections/community.general/pull/3425)
```suggestion
  - mail - added the ``ehlohost`` parameter which allows for manual override of the host used in SMTP EHLO (https://github.com/ansible-collections/community.general/pull/3425).
```

2021-09-23 21:17 UTC, j20d commented
> Outside of the changelog this looks good. I don't think this is a candidate for [integration tests](https://github.com/ansible-collections/community.general/blob/main/tests/integration/targets/mail/tasks/main.yml) given the nature of the feature, but please take a look and confirm.

Adding an integration test seems fair, did so.

2021-09-23 22:27 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-09-24 05:30 UTC, merged

2021-09-24 05:30 UTC, felixfontein commented
@j20d thanks for contributing this!
@Ajpantuso thanks for reviewing!