Copy the permissions along with file for jboss module
ansible-collections/community.general pull request #3426
Opened 2021-09-24 03:52 UTC by xcompass

##### SUMMARY

The deployment file is copied with file content only. The file
permission is set to 440 and belongs to root user. When the
JBossI(Wildfly) server is running under non root account, it can't read
the deployment file.

With is fix, the correct permission can be set from previous task for JBoss
server to pickup the deployment file.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Jboss

##### ADDITIONAL INFORMATION

```paste below

```

2021-09-24 05:20 UTC, felixfontein reviewed
Thanks for your contribution! Can you please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)? Thanks.

2021-09-24 06:41 UTC, xcompass commented
@felixfontein done.

2021-09-24 13:38 UTC, Ajpantuso requested changes
Just a few comments to start with.

2021-09-24 13:38 UTC, Ajpantuso commented on plugins/modules/web_infrastructure/jboss.py
> +        shutil.copy(src, os.path.join(deploy_path, deployment))
```suggestion
        module.preserved_copy(src, os.path.join(deploy_path, deployment))
```

Taking this a step further I would use the `Ansible` provided [utilities](https://github.com/ansible/ansible/blob/58b03be4178fda12a7d082ae9fd54104229e9d99/lib/ansible/module_utils/basic.py#L1623) if appropriate to preserve as much of the source file's attributes as possible.

2021-09-24 13:38 UTC, Ajpantuso commented on changelogs/fragments/3367-copy-permissions-along-with-file-for-jboss-module.yml
> +    the deployment file.
```suggestion
    JBoss I(WildFly) server is running under non-root user, it is unable to read
    the deployment file (https://github.com/ansible-collections/community.general/pull/3426).
```

2021-09-24 13:38 UTC, Ajpantuso commented on plugins/modules/web_infrastructure/jboss.py
> +            shutil.copy(src, os.path.join(deploy_path, deployment))
Same here.

2021-09-24 17:42 UTC, xcompass commented
Updated according to suggestion.

2021-09-25 14:04 UTC, Ajpantuso requested changes
Just some more updates to the changelog fragment.

2021-09-25 14:04 UTC, Ajpantuso commented on changelogs/fragments/3426-copy-permissions-along-with-file-for-jboss-module.yml
> +    the deployment file. (https://github.com/ansible-collections/community.general/pull/3426)
```suggestion
    file permission is set to ``440`` and belongs to root user. When the
    JBoss ``WildFly`` server is running under non-root user, it is unable to read
    the deployment file (https://github.com/ansible-collections/community.general/pull/3426).
```

2021-09-28 21:46 UTC, Ajpantuso approved these changes
LGTM, @xcompass just confirming if you've tested in your environment successfully?

2021-09-28 21:50 UTC, xcompass commented
@Ajpantuso Yes, I'm using it as local module in my environment.

2021-09-29 04:51 UTC, merged

2021-09-29 04:51 UTC, felixfontein commented
@xcompass thanks for fixing this!
@Ajpantuso thanks for reviewing!