Default admin and external to None and sanitize arguments
ansible-collections/community.general pull request #3484
Opened 2021-09-30 15:28 UTC by stgrace

##### SUMMARY

When gitlab_username is an admin-account, the task removes the admin privileges as isadmin defaults to false .

See #3483 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

gitlab_user

2021-09-30 15:33 UTC, felixfontein requested changes
As mentioned in #3483, this is a breaking change which should not be made without a long enough deprecation period.

2021-12-05 21:16 UTC, felixfontein commented
@stgrace are you still working on this?

needs_info

2021-12-05 21:18 UTC, stgrace commented
@felixfontein I'll take a look at it asap. Have some other priorities untill Tuesday, so will be Wednesday

2022-04-15 10:49 UTC, russoz commented
hi @stgrace is this something you are still able to work on?

needs_info

2022-06-22 06:30 UTC, closed without merging