change ip4 type to list of str
ansible-collections/community.general pull request #3738
Opened 2021-11-15 21:58 UTC by haddystuff

##### SUMMARY
This PR adds support of multiple ipv4 addresses on one interface which was requested here #1088.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/modules/net_tools/nmcli.py

##### ADDITIONAL INFORMATION
As it turns out changing type of parameter is enough to make it work.
Now list can be used in ```ip4``` parameter in playbook, but string is also working, so it's backwards compatible.
I didn't add any additional test or documentation just for now. I think such change need to be discussed first.

2021-11-16 06:23 UTC, felixfontein commented
Thanks for your contribution! Can you please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)? Thanks.

2021-11-16 09:04 UTC, haddystuff commented
ok, let me just add some tests and examples to documentation

2021-11-17 17:56 UTC, haddystuff commented
Adding multiple addresses support for ip6 request more time to implement, so i'll make another pull request later on.

2021-11-18 23:25 UTC, Ajpantuso requested changes
Other than the changelog fragment this looks good. Pulled this locally for testing and haven't found any issues.

2021-11-18 23:25 UTC, Ajpantuso commented on changelogs/fragments/1088-nmcli_add_multiple_addresses_support.yml
> +  - add multiple addresses support for ip4 parameter
```suggestion
  - nmcli - add multiple addresses support for ``ip4`` parameter
```

2021-11-19 00:08 UTC, Ajpantuso approved these changes
LGTM

2021-11-19 06:07 UTC, merged

2021-11-19 06:07 UTC, felixfontein commented
@haddystuff thanks for implementing this!
@Ajpantuso thanks for reviewing!