Fix module failure due to itertools.izip_longest
ansible-collections/community.general pull request #4211
Opened 2022-02-17 07:43 UTC by boris-vasilev

##### SUMMARY

Fixes #4206

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

imc_rest

##### ADDITIONAL INFORMATION

Fixes module failure due to the usage of itertools.izip_longest which is missing in Python 3.
Used ansible.module_utils.six.moves.zip_longest which is works in both Python 2 and 3.

```paste below

```

2022-02-17 07:58 UTC, Akasurde requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2022-02-17 08:00 UTC, Akasurde commented on plugins/modules/remote_management/imc/imc_rest.py
> +        return [merge(alpha, beta) for (alpha, beta) in zip_longest(one, two)]
remove


```
	import itertools
```

2022-02-20 08:24 UTC, felixfontein approved these changes

2022-02-20 08:40 UTC, merged

2022-02-20 08:41 UTC, felixfontein commented
@boris-vasilev thanks for fixing this!
@Akasurde thanks for reviewing!