keycloak_client: add default_client_scopes and optional_client_scopes
ansible-collections/community.general pull request #4385
Opened 2022-03-21 22:12 UTC by alubbock

##### SUMMARY

Add `default_client_scopes` and `optional_client_scopes` parameters to `keycloak_client`. Partially resolves #2763.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

keycloak_client

##### ADDITIONAL INFORMATION

This PR adds the ability to set default and optional client scopes for a Keycloak client. This is useful for openid-connect clients that have requirements for specific scopes/claims.

Before:
```
failed: [localhost] ..."msg": "Unsupported parameters for (community.general.keycloak_client) module: default_client_scopes..."...
```
After:
```
ok: [localhost]
```

2022-03-22 06:39 UTC, felixfontein reviewed
Thanks for your contribution! I've added some first comments.

2022-03-22 06:39 UTC, felixfontein commented on changelogs/fragments/4385-keycloak-client-default-optional-scopes.yml
> +  - keycloak_client - add default_client_scopes and optional_client_scopes parameters.
```suggestion
  - keycloak_client - add ``default_client_scopes`` and ``optional_client_scopes`` parameters.
```

2022-03-22 06:39 UTC, felixfontein commented on plugins/modules/identity/keycloak/keycloak_client.py
> +        elements: str
```suggestion
        elements: str
        version_added: 4.7.0
```

2022-03-22 06:39 UTC, felixfontein commented on plugins/modules/identity/keycloak/keycloak_client.py
> +        elements: str
```suggestion
        elements: str
        version_added: 4.7.0
```

2022-03-22 08:13 UTC, alubbock commented
@felixfontein I've implemented all of your suggestions - thanks for your feedback.

2022-03-23 08:24 UTC, russoz requested changes
@alubbock I am not familiar with Keycloak, so not sure if I am missing something, but it looks like these parameters were added to the module interface and but they are not used anywhere else.

Could you please double check and/or clarify that to me? TIA

2022-03-23 10:20 UTC, alubbock commented
@russoz The new parameters are [picked up dynamically and passed to the Keycloak API](https://github.com/ansible-collections/community.general/blob/eb4495b716a081e9150e7a5edeef3bd6b19ef456/plugins/modules/identity/keycloak/keycloak_client.py#L794-L810), so no further code is needed to get them working.

They're not used by any other ansible modules in this collection if that's what you mean, but the use case is for the user to create a "client scope" using `community.general.keycloak_clientscope`, then supply the name of that client scope as part of a list to `default_client_scopes` or `optional_client_scopes` in `community.general.keycloak_client`. I've tested these parameters against the latest Keycloak 17.0.0 (Quarkus) and they do update Keycloak as intended.

2022-03-24 01:52 UTC, russoz commented
Alright, thanks for the clarification!

2022-03-24 01:53 UTC, russoz approved these changes
LGTM

2022-03-24 06:10 UTC, felixfontein commented
Let's keep this open for a few more days (say until beginning of next week?) in case someone else wants to commit.

2022-03-28 19:28 UTC, merged

2022-03-28 19:28 UTC, felixfontein commented
@alubbock thanks for contributing this!
@russoz thanks for reviewing!

2022-05-03 19:41 UTC, isolovey commented
@alubbock I tried setting the `default_client_scopes` option on `keycloak_client` task but it did not work. Examining the task's return dict, I can see it being sent to the Keycloak API endpoint (in the `proposed` value), but `end_state` contains the old value, ignoring insertions and/or deletions.

Keycloak API specifies a [separate endpoint](https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_adddefaultclientscope) for inserting/deleting default client scopes, and using them works as expected. They are not used in in this PR.

Just curious what the difference between our setups is. I'm running 17.0.1 on Wildfly, but it seems unlikely that the backend framework / app server could be the culprit. Any thoughts?