[datadog_monitor] Remove '@' from API response
ansible-collections/community.general pull request #4428
Opened 2022-03-30 23:17 UTC by albertvaka

##### SUMMARY
In #1338 we marked the the `notification_message` field as `no_log`. This is not always effective in removing the message string from the events generated when the task runs, though, since sometimes the server response contains a message string that isn't exactly equal to the input string specified in `notification_message`, so it doesn't get masked. This could happen, for example, if the input string has leading spaces, because the server trims the message string in the response. The server might also change double quotes to single quotes or do other transformations.  

This is the same problem we tried to fix in #1338 when the `notification_message` contains an `@<name>` to page team `<name>` and this also triggers a page when sending an event to Datadog from the [Datadog Ansible callback](https://github.com/DataDog/ansible-datadog-callback) after the task runs. For this reason, we want to modify the message so the `@<name>` isn't there even when not masked.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
`datadog_monitor`

2022-03-31 02:29 UTC, Akasurde requested changes

2022-03-31 02:29 UTC, Akasurde commented on plugins/modules/monitoring/datadog/datadog_monitor.py
> +            message=dict(no_log=True),
`message` is internally used by the Ansible Core engine for sys logging. Please use a different parameter name.

2022-03-31 18:21 UTC, felixfontein commented
I'm not sure what this PR is trying to achieve. The module does not have a `message` option, so you cannot do anything similar to #1338. This PR adds a new option that isn't used by the module.

2022-04-01 01:55 UTC, albertvaka commented
Sorry @felixfontein, I assumed that `no_log` filtered by key and not by value. I've tried a different approach to solve the problem we are seeing from some customers.

2022-04-01 21:10 UTC, felixfontein commented
> This is the same problem we tried to fix in #1338 when the `notification_message` contains an `@<name>` to page team `<name>` and this also triggers a page when sending an event to Datadog from the [Datadog Ansible callback](https://github.com/DataDog/ansible-datadog-callback) after the task runs. For this reason, we want to modify the message so the `@<name>` isn't there even when not masked.

Wouldn't it make more sense to modify the datadog callback so that it handles the output of the datadog_monitor module specially by modifying the `@`?

2022-04-04 10:48 UTC, albertvaka commented
The reason I didn't do that is because someone might actually be sending `@<something>` on purpose from somewhere else so they get paged/notified... but it's definitely an option to implement it there if you think this change doesn't fit here. Let me know what you think :)

2022-04-04 12:46 UTC, albertvaka commented
I've changed my mind... it definitely makes more sense to do this on the callback side as you pointed out. I've opened a PR there: https://github.com/DataDog/ansible-datadog-callback/pull/68

2022-04-04 12:46 UTC, closed without merging