Fix creation of srv entries #5167
ansible-collections/community.general pull request #5191
Opened 2022-08-25 13:27 UTC by martin-schlossarek

##### SUMMARY
Fixes #5167 

This PR removes the splicing of the record entry which resulted in malformed api calls. record must be the name of the subdomain or "@"

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
cloudflare_dns

##### ADDITIONAL INFORMATION
See: https://github.com/ansible-collections/community.general/issues/5167#issuecomment-1227227916

2022-09-03 11:39 UTC, felixfontein requested changes
Pending discussion in #5167.

2022-11-03 05:58 UTC, felixfontein commented
Please note that in #5461 the collection repository was restructured to remove the directory tree in plugins/modules/, and the corresponding tree in tests/unit/plugins/modules/. Your PR modifies files in this directory structure, and unfortunately now has some conflicts, potentially because of this. Please **rebase** with the current `main` branch to remove the conflicts.

2022-11-03 14:01 UTC, martin-schlossarek commented
Sorry, I didn't have time to look at the problem further. In the meantime my use case to be able to set SRV entries has also become obsolete.

I withdraw the pull request, if that's ok?

Nevertheless, I think it should be mentioned in the documentation that SRV entries must always have a FQDN specified. For other entries this is not the case.

2022-11-03 14:01 UTC, closed without merging

2022-11-04 05:49 UTC, felixfontein commented
> Nevertheless, I think it should be mentioned in the documentation that SRV entries must always have a FQDN specified. For other entries this is not the case.

Do you want to create a PR for that? :)