passwordstore lookup: allow to pass options as lookup options
ansible-collections/community.general pull request #5444
Opened 2022-10-30 19:41 UTC by felixfontein

##### SUMMARY
Something which should have been done a long time ago: allow to pass in options as lookup options instead of insisting that they have to be parsed from the terms.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
passwordstore lookup plugin

2022-10-30 20:41 UTC, felixfontein commented
CC @baierjan @bergmannf @grembo @phaer @TheLastProject since you contributed to this plugin before. Would be glad if you could review this / try this out!

2022-10-30 21:43 UTC, baierjan approved these changes
That is quite a big change, but it definitely looks cleaner that way. Fine by me. 👍🏻

2022-10-31 15:36 UTC, TheLastProject requested changes
I agree this is generally an improvement and improves consistency with other modules. But it will hurt people a bit as they'll have to refactor their Ansible code. Definitely needs a major release and needs to be marked as a major change imho.

Also note I haven't tested this, just looking at how the code looks to me.

2022-10-31 15:36 UTC, TheLastProject commented on changelogs/fragments/5444-passwordstore-options.yml
> +  - "passwordstore lookup plugin - allow options to be passed lookup options instead of being part of the term strings (https://github.com/ansible-collections/community.general/pull/5444)."
I really disagree this should be put under `minor_changes` as this requires a code refactor. It should be considered a breaking change.

2022-10-31 17:23 UTC, felixfontein commented
> But it will hurt people a bit as they'll have to refactor their Ansible code.

But why? Everything that worked so far still works. (Except if you passed lookup parameters and expected them to not work.)

This PR only allows a new (better) way to provide options. The old way still works (it should get deprecated eventually, but definitely not now).

2022-10-31 17:54 UTC, TheLastProject approved these changes

2022-10-31 17:55 UTC, TheLastProject commented
Nevermind them, misunderstood the code in that case :)

2022-11-02 19:17 UTC, merged

2022-11-02 19:17 UTC, felixfontein commented
@baierjan @TheLastProject thanks a lot for reviewing this!