sorcery: moved import to top
ansible-collections/community.general pull request #6525
Opened 2023-05-16 11:09 UTC by russoz

##### SUMMARY

Moved import stmt from bottom to the top-ish of the file

##### ISSUE TYPE

- Refactoring Pull Request

##### COMPONENT NAME

sorcery

2023-05-16 12:34 UTC, vaygr requested changes

2023-05-16 12:34 UTC, vaygr commented on changelogs/fragments/6525-sorcery-import.yaml
> +  - sorcey - minor refactor (https://github.com/ansible-collections/community.general/pull/6525).
```suggestion
  - sorcery - minor refactor (https://github.com/ansible-collections/community.general/pull/6525).
```

2023-05-16 19:53 UTC, russoz commented on changelogs/fragments/6525-sorcery-import.yaml
> +  - sorcey - minor refactor (https://github.com/ansible-collections/community.general/pull/6525).
Thanks for spotting it!

2023-05-17 17:00 UTC, felixfontein approved these changes
Will merge for 7.1.0.

2023-05-29 16:54 UTC, merged

2023-05-29 16:54 UTC, felixfontein commented
@russoz thanks for your contribution!
@vaygr thanks for reviewing!