Fixed gitlab_*_variable when using purge
ansible-collections/community.general pull request #7251
Opened 2023-09-12 14:32 UTC by MaxBidlingmaier

##### SUMMARY
Hotfix to 7.4 release deleting all GitLab variables

Fixes #7250 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

affected modules are:
- gitlab_group_variable
- gitlab_project_variable

##### ADDITIONAL INFORMATION
```paste below

```

2023-09-12 20:19 UTC, lgatellier requested changes
Thanks for your contribution !

Can you squash all your commits in a single self-explaining commit ?

Would you also mind adding an integration test to ensure this bug won't occur in eventual future variable attributes change ?

2023-09-12 20:19 UTC, lgatellier commented on plugins/modules/gitlab_group_variable.py
> +        # please mind whenever chaning the variables dict to also change module_utils/gitlab.py's
```suggestion
        # please mind whenever changing the variables dict to also change module_utils/gitlab.py's
```

2023-09-12 20:19 UTC, lgatellier commented on plugins/modules/gitlab_project_variable.py
> +        # please mind whenever chaning the variables dict to also change module_utils/gitlab.py's
```suggestion
        # please mind whenever changing the variables dict to also change module_utils/gitlab.py's
```

2023-09-12 20:19 UTC, lgatellier commented on changelogs/fragments/7251-gitlab-variables-deleteing-all-variables.yml
> +  - "gitlab_group_variable deletes all variables when used with purge: true due to missing 'raw' property in KNOWN attributes"
```suggestion
  - gitlab_project_variable deletes all variables when used with ``purge=true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250).
  - gitlab_group_variable deletes all variables when used with ``purge=true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250).
```

2023-09-13 05:32 UTC, felixfontein commented on changelogs/fragments/7251-gitlab-variables-deleteing-all-variables.yml
> +  - "gitlab_group_variable deletes all variables when used with purge: true due to missing 'raw' property in KNOWN attributes"
```suggestion
  - "gitlab_project_variable - deleted all variables when used with ``purge: true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250, https://github.com/ansible-collections/community.general/pull/7251)."
  - "gitlab_group_variable - deleted all variables when used with ``purge: true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250, https://github.com/ansible-collections/community.general/pull/7251)."
```

2023-09-13 17:28 UTC, MaxBidlingmaier commented
> Thanks for your contribution !
> 
> Can you squash all your commits in a single self-explaining commit ?
> 
> Would you also mind adding an integration test to ensure this bug won't occur in eventual future variable attributes change ?

Hm, I think the whole code of the two modules somehow got  broken since I contributed some time ago, so it would be better to fix the code then work around the problem with additional tests. 
For purging we do not need to compare the full property list (where depending on the GitLab version the structure could be different). In fact the current code only works for spefcific GitLab versions. So if we would change to just compare variable names again for that part we would ensure that it cannot happen.

2023-09-16 07:41 UTC, felixfontein commented on changelogs/fragments/7251-gitlab-variables-deleteing-all-variables.yml
> +  - gitlab_group_variable deletes all variables when used with ``purge=true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250
```suggestion
  - gitlab_project_variable - deleted all variables when used with ``purge=true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250).
  - gitlab_group_variable - deleted all variables when used with ``purge=true`` due to missing ``raw`` property in KNOWN attributes (https://github.com/ansible-collections/community.general/issues/7250).
```

2023-09-20 17:26 UTC, felixfontein commented
@lgatellier is it OK for you to merge this, so that the issue is fixed? I guess additional things (more tests, ...) can still be added in follow-up PRs.

2023-09-20 17:28 UTC, lgatellier commented
> @lgatellier is it OK for you to merge this, so that the issue is fixed? I guess additional things (more tests, ...) can still be added in follow-up PRs.

Yep, LGTM ! 🚀

2023-09-20 17:37 UTC, merged

2023-09-20 17:37 UTC, felixfontein commented
@MaxBidlingmaier thanks for fixing this!
@lgatellier thanks for reviewing!

2023-09-20 18:08 UTC, markuman commented
Oh damn, it was introduced while adding the `raw` feature https://github.com/ansible-collections/community.general/pull/7132  
thx for fixing!

2023-09-20 18:09 UTC, markuman commented
I wonder if the integration test covers it ...

2023-09-20 18:19 UTC, markuman commented
yeah, integration test would have covered it :-/

```
TASK [Install required libs] *****************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [purge all variables for check_mode test] ***********************************************************************************************************************************************************************************************
changed: [localhost]

TASK [add a variable value in check_mode] ****************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [check_mode state must be changed] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [apply add value from check_mode test] **************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [state must be changed] *****************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [test new format] ***********************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [state must be not changed] *************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "gitlab_project_variable_state is not changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

So we lack here on CI against a gitlab instance.  
Maybe someone has some time to create an integration test against a gitlab container in github actions.