homebrew_cask: Consider greedy option for upgrades too
ansible-collections/community.general pull request #798
Opened 2020-08-18 10:52 UTC by janernsting

##### SUMMARY
`brew-cask` accepts `--greedy` for both the upgrade and outdated command (see [their usage reference](https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md)). So far, only the check for outdated casks considered the Ansible option.

This change aligns Ansible's use of the greedy option.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
homebrew_cask

2020-08-18 10:58 UTC, felixfontein commented
You need a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

2020-08-27 06:54 UTC, janernsting commented
Does the add changelog fragment match your needs, @felixfontein?

2020-08-27 06:57 UTC, felixfontein commented on changelogs/fragments/798-homebrew-cask-greedy-for-upgrades-too.yaml
> +  - homebrew_cask - consider `greedy` option for upgrade_all, too (https://github.com/ansible-collections/community.general/pull/798)
```suggestion
  - homebrew_cask - consider ``greedy`` option for upgrade_all, too (https://github.com/ansible-collections/community.general/pull/798)
```

2020-08-27 06:58 UTC, felixfontein commented
@janernsting sorry I missed the update. Looks good, but it uses reStructuredText formatting and not MarkDown, so it should be double backticks.

@Akasurde @danieljaouen @enriclluelles @indrajitr @kyleabenson @martinm82 as maintainers of the module, could you please look at the change itself whether it is good?

2020-08-27 16:33 UTC, felixfontein commented on changelogs/fragments/798-homebrew-cask-greedy-for-upgrades-too.yaml
> +  - homebrew_cask - consider ``greedy`` option for upgrade_all, too (https://github.com/ansible-collections/community.general/pull/798)
```suggestion
  - homebrew_cask - consider ``greedy`` option for upgrade_all, too (https://github.com/ansible-collections/community.general/pull/798).
```
Sorry, I totally missed that period...

2020-08-28 09:28 UTC, janernsting commented
@felixfontein I amended the previous commit to include a trailing period.

2020-10-21 06:42 UTC, Andersson007 commented
@janernsting thanks for the PR!
@martinm82 could you please take a look?

2020-11-11 09:57 UTC, martinm82 approved these changes

2020-11-11 10:02 UTC, martinm82 requested changes

2020-11-11 10:02 UTC, martinm82 commented on plugins/modules/packaging/os/homebrew_cask.py
> +        if self.greedy:
Please update as well the documentation (`DOCUMENTATION`) of the `greedy` attribute . Right now it mentions only that it is used for outdated command

2020-11-24 07:14 UTC, felixfontein commented
@janernsting can you please take a look at @martinm82's review comment?

2020-12-12 15:54 UTC, janernsting commented
Thank you for your heads-up, @felixfontein. I am likely to get this done with next week or in between Xmas and New Years eve.

2021-02-26 09:07 UTC, felixfontein commented
@janernsting are you still working on this?

needs_info

2021-03-28 19:59 UTC, felixfontein commented
Closing since there was no more reaction. @janernsting if you're interested again in working on this, please ping me. If someone else is interested in continuing this PR, please also write it here so we can coordinate.

2021-03-28 19:59 UTC, closed without merging