Implement keycloak authorization resources
ansible-collections/community.general pull request #8165
Opened 2024-03-29 09:47 UTC by maximilianpohle

##### SUMMARY

Adding `keycloak_authz_resource` module.

##### ISSUE TYPE

- New Module/Plugin Pull Request

##### COMPONENT NAME

keycloak_authz_resource

##### ADDITIONAL INFORMATION

```paste below

```

2024-03-29 18:27 UTC, felixfontein commented
Thanks for your contribution! In case you didn't do that yet, please check out the section in CONTRIBUTING.md on creating new modules (https://github.com/ansible-collections/community.general/blob/main/CONTRIBUTING.md#creating-new-modules-or-plugins) :)

2024-05-12 08:01 UTC, felixfontein commented
Ping @maximilianpohle

2024-05-26 19:04 UTC, maximilianpohle commented
@felixfontein still on it, please give me some time.

Need to check the contribution notes still.

2024-06-01 21:24 UTC, felixfontein commented on plugins/modules/keycloak_authz_resource.py
> +version_added: 8.6.0
```suggestion
version_added: 9.1.0
```

2024-06-01 21:24 UTC, felixfontein commented on plugins/modules/keycloak_authz_resource.py
> +    - Maximilian Pohle (@mattock)
```suggestion
    - Maximilian Pohle (@maximilianpohle)
```

2024-09-07 03:31 UTC, armkeh requested changes
Nitpick: I found a few places which refer to permissions, scopes or groups instead of resources.

2024-09-07 03:31 UTC, armkeh commented on plugins/module_utils/identity/keycloak/keycloak.py
> +            self.fail_open_url(e, msg='Could not delete permission %s for client %s in realm %s: %s' % (id, client_id, realm, str(e)))
Nitpick: I found a few places which refer to the resource as a permission or a scope.
```suggestion
            self.fail_open_url(e, msg='Could not delete resource %s for client %s in realm %s: %s' % (id, client_id, realm, str(e)))
```

2024-09-07 03:31 UTC, armkeh commented on plugins/module_utils/identity/keycloak/keycloak.py
> +            self.fail_open_url(e, msg='Could not create update permission %s for client %s in realm %s: %s' % (payload['name'], client_id, realm, str(e)))
```suggestion
            self.fail_open_url(e, msg='Could not create update resource %s for client %s in realm %s: %s' % (payload['name'], client_id, realm, str(e)))
```

2024-09-07 03:31 UTC, armkeh commented on plugins/modules/keycloak_authz_resource.py
> +            - The clientId of the keycloak client that should have the authorization scope.
```suggestion
            - The clientId of the keycloak client that should have the authorization resource.
```

2024-09-07 03:31 UTC, armkeh commented on plugins/modules/keycloak_authz_resource.py
> +- name: Manage scope-based Keycloak authorization resource
```suggestion
- name: Manage Keycloak authorization resource
```

2024-09-07 03:31 UTC, armkeh commented on plugins/modules/keycloak_authz_resource.py
> +    # Get current state of the permission using its name as the search
```suggestion
    # Get current state of the resource using its name as the search
```

2024-09-07 03:31 UTC, armkeh commented on plugins/modules/keycloak_authz_resource.py
> +            result['msg'] = 'Would remove permission'
```suggestion
            result['msg'] = 'Would remove resource'
```

2024-09-07 03:31 UTC, armkeh commented on tests/integration/targets/keycloak_authz_resource/readme.adoc
> +  * creating, modifying and deleting some keycloak groups
```suggestion
  * Creating and deleting a Keycloak client with (human-readable) ID `authz` (configurable in `./vars/main.yml`).
  * Creating, modifying and deleting resources on that client.
```

2025-04-22 05:03 UTC, closed without merging