Docs. Remove helpers.
ansible-collections/community.general pull request #8647
Opened 2024-07-16 13:01 UTC by vbotka

##### SUMMARY

Let's remove the helpers. Quoting from #8645

> ... dynamic way to generate documentations within the repository ... is not something we would like to do. There are processes that read (and expect) .rst files only within that directory.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

2024-07-16 21:19 UTC, felixfontein requested changes
At least `lists_mergeby` should be kept.

2024-07-16 21:50 UTC, vbotka commented
> At least `lists_mergeby` should be kept.

This is up to you.

2025-02-16 04:02 UTC, russoz commented
@felixfontein I am revisiting this pending PR. It is not entirely clear to me how we should handle it. I assumed we did not want to have dynamic code under the `docs/docsite` tree, hence we should remove the `helper` subdirs. It must be noticed that, once the content in `docs/docsite/rst` has been generated, that logic in `helpers` is not used.

Then you commented that "`lists_mergeby` should be kept". Are you referring to the code in `helper`? Because that is what this PR is about. The contents in `rst` is not touched by this PR.

I have mixed feelings about this: on one hand it might be interesting to have the docs showcasing actual test results, on the other hand, if we were to embrace that idea I think we might want to create a better, integrated, structure for this, potentially tapping on both unit and integration tests. For that, we would likely need to create standard structures/elements in the 3 subdirectories: `docs/`, `tests/integration` and `tests/unit`. I reckon that would be a slightly larger piece of work than just a single PR. Anyways, I digress.

So, back to this PR, could you please clarify what you mean it should be kept? Are you actually referring to the playbooks and accompanying files in `docs/docsite/helper/lists_mergeby` ? Again, the RST files generated by those playbooks are already commited. 

Appreciate your thoughts on the matter. TIA

2025-02-16 04:27 UTC, russoz commented
One additional comment here, after I tumbled deeper into the rabbit hole. There are these 3 distinct PRs related to this matter:
* this very one: #8647 
* one for new docs: #8645 
* and one (merged): #8482 

After reading comments in all three, and my own rumblings in the previous comment here, I am leaning towards an idea of a solution that would look like this: 
* `helper` would contain only data, no code at all, 
* the logic of generating docs from templates (part of that data) + tests and their outputs would not exist within this repository, rather it would be an external tool
  * that tool would provide standard mechanisms for dealing with the integration tests and the templates
  * that tool would perform validations on the structure and fail if any test or template is not compliant
  * that tool would, optionally, generate the files directly into the `rst` folder for committing, or elsewhere for debugging (though using `rst` in a separate branch should probably be enough).

Further automation and segregation of duties might be applied here, that's just a brain dump.

About this PR (and the others), I think we might be lenient and keep that working code in place, but we should block other plugins from creating new "helpers" in the same way.

@vbotka @felixfontein what do you think?

2025-02-16 04:51 UTC, vbotka commented
Still the same. Remove the helpers or keep them at your discretion and maintenance. Then, I'll take care of the docs.

2025-02-23 21:22 UTC, russoz commented
ping @felixfontein

2025-02-25 06:52 UTC, felixfontein commented
> After reading comments in all three and my own rumblings in the previous comment here, I am leaning towards an idea of a solution that would look like this:
> 
>     * `docs/docsite/helper` would contain only data, **no code at all**,

That would be preferred. But, that requires code somewhere. What you describe next:

>     * the logic of generating docs from templates (part of that data) + tests and their outputs would not exist within this repository, rather it would be an **external tool**
>       
>       * that tool would provide standard mechanisms for dealing with the integration tests and the templates
>       * that tool would perform validations on the structure and fail if any test or template is not compliant
>       * that tool would, optionally, generate the files directly into the `rst` folder for committing, or elsewhere for debugging (though using `rst` in a separate branch should probably be enough).

would be my favorite solution, but right now we don't have such a tool, neither a generic one inside the repo, nor one outside. Until that happens, we should keep the helpers.

Generally, about the tool: I think it's somewhat comparable to Python doctests (https://docs.python.org/3/library/doctest.html). My idea would be that the tool allows you to provide some hidden setup code as comments in the RST files, some public code in there that defines what has to be run (together with the hidden setup code), and the output (resp. some part of it). The tool would have two modes: a) update the output, b) check the output (for CI, to point out that the output needs to be updated).

> Further automation and segregation of duties might be applied here, that's just a brain dump.

CI should run the tool to make sure no updates are needed, and it should be somewhat easy to use (especially for not so experienced contributors).

Note that I tried out using docutils to find code blocks to lint YAML in them in https://github.com/ansible/ansible-documentation/pull/2385, maybe something similar could be used to implement this. Or maybe the tool should operate on a lower level where it simply treats RST documents as a text file and uses pattern matching for finding the appropriate places. (Downside: if you put an example for this tool inside a code block, the tool will likely not notice that it's inside a code block and still process it...)

2025-02-25 07:05 UTC, vbotka commented
> ... right now we don't have such a tool, neither a generic one inside the repo, nor one outside. Until that happens, we should keep the helpers.

For the record. I don't maintain docs/docsite/helper/* anymore.

2025-02-26 19:51 UTC, russoz commented
Hi @gundalow, you asked before about how the development and tools team could help, this issue here might be the kickstart for something interesting.

2025-07-17 20:22 UTC, felixfontein commented
I'm currently working on replacing these helpers by antsibull-docs' ansible-output subcommand; I'm doing related work in #10421, for these ones I need some more help from ansible-core's side to avoid the community.general.yaml callback (mainly https://github.com/ansible/ansible/pull/85497).

In any case, if you rebase this, I'll merge the PR.

2025-08-10 12:14 UTC, merged

2025-08-10 12:15 UTC, felixfontein commented
@vbotka thanks for the PR!